from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from ..config import OmniIntentsConfig
from ..llm.base import LLMClient
from ..types import AgentRecommendation, AgentType, Capability, PipelineTrace, TaskPlan
from ..utils.json_utils import extract_first_json_object, truncate, dumps_pretty
from ..utils.validate import validate_agent_json
from .decision_tree import ExplicitDecisionTree, ImplicitDecisionTree, cost_optimized_pick


@dataclass
class AgentGPT:
    """AgentGPT module (paper 6.3).

    - Recommends the best agent type for tasks generated by TaskGPT
    - Uses implicit decision tree + cost optimization
    - Optionally uses an LLM to pick among candidates (still validated and cost-aware)
    """

    llm: LLMClient
    config: OmniIntentsConfig = OmniIntentsConfig()
    implicit_tree: Optional[ImplicitDecisionTree] = None
    explicit_tree: Optional[ExplicitDecisionTree] = None

    use_llm_selection: bool = False

    def __post_init__(self) -> None:
        self.implicit_tree = self.implicit_tree or ImplicitDecisionTree(config=self.config)
        self.explicit_tree = self.explicit_tree or ExplicitDecisionTree(config=self.config)

    def recommend(self, task_plan: TaskPlan, trace: Optional[PipelineTrace] = None) -> AgentRecommendation:
        required: List[Capability] = task_plan.required_capabilities()
        candidates, path = self.implicit_tree.recommend_candidates_with_path(task_plan)  # type: ignore[union-attr]

        if trace is not None and self.config.enable_trace:
            trace.add(
                "agentgpt.candidates",
                {"required_capabilities": [c.value for c in required], "candidates": [c.value for c in candidates], "decision_path": path},
            )

        # Optional: ask LLM to pick among candidates
        if self.use_llm_selection:
            llm_choice = self._llm_pick_agent(task_plan, candidates, trace=trace)
            if llm_choice is not None:
                # Put LLM choice first to influence cost picker if it also satisfies all
                candidates = [llm_choice] + [c for c in candidates if c != llm_choice]

        agent, satisfied, missing, cost = cost_optimized_pick(
            candidates=candidates,
            required=required,
            agent_capabilities=self.config.agent_capabilities,  # type: ignore[arg-type]
            agent_cost=self.config.agent_cost,  # type: ignore[arg-type]
        )

        rationale = self._rationale(agent, required, missing, path)
        rec = AgentRecommendation(
            agent_type=agent,
            rationale=rationale,
            estimated_cost=cost,
            satisfied_capabilities=satisfied,
            missing_capabilities=missing,
        )

        if trace is not None and self.config.enable_trace:
            trace.add("agentgpt.recommendation", rec.to_json_dict())

        return rec

    def _llm_pick_agent(self, task_plan: TaskPlan, candidates: List[AgentType], trace: Optional[PipelineTrace] = None) -> Optional[AgentType]:
        prompt = self._build_prompt(task_plan, candidates)
        if trace is not None and self.config.enable_trace:
            trace.add("agentgpt.prompt", {"prompt": truncate(prompt, self.config.max_prompt_chars_in_trace)})

        llm_result = self.llm.complete(prompt, temperature=0.2, max_tokens=300)
        if trace is not None and self.config.enable_trace:
            trace.add("agentgpt.llm_output", {"text": truncate(llm_result.text, self.config.max_prompt_chars_in_trace)})

        data = extract_first_json_object(llm_result.text) or {}
        ok, _ = validate_agent_json(data, candidates=candidates)
        if not ok:
            return None
        try:
            return AgentType(str(data.get("agent_type")).strip())
        except Exception:
            return None

    def _build_prompt(self, task_plan: TaskPlan, candidates: List[AgentType]) -> str:
        instruction = (
            "You are AgentGPT. Choose the best agent type to execute the given task plan. "
            "Analyze required functionalities (speech, visual, physical) and minimize cost. "
            "Return ONLY JSON."
        )
        prompt = "\n\n".join(
            [
                instruction,
                "AGENT_RECOMMENDATION_JSON",
                "### INPUT",
                "TASK_PLAN_JSON:",
                dumps_pretty(task_plan.to_json_dict()),
                "CANDIDATES:",
                ", ".join([c.value for c in candidates]),
                "### OUTPUT FORMAT",
                "Return JSON with keys: agent_type (one of candidates), rationale (string).",
            ]
        )
        return prompt

    def _rationale(self, agent: AgentType, required: List[Capability], missing: List[Capability], path: List[str]) -> str:
        path_text = " -> ".join(path) if path else "implicit tree"
        if not missing:
            return (
                f"Selected {agent.value} because it satisfies all required capabilities "
                f"({', '.join([c.value for c in required])}) with low estimated cost. "
                f"Decision path: {path_text}."
            )
        return (
            f"Selected {agent.value} as the best available trade-off: it satisfies "
            f"{', '.join([c.value for c in required if c not in missing])} but is missing {', '.join([c.value for c in missing])}. "
            f"Decision path: {path_text}. Consider upgrading the agent or refining the plan."
        )
